services:
  # API service
  api-service:
    container_name: api-service
    build:
      args:
        PROJECT_NAME: ${PROJECT_NAME}
      context: ./
      dockerfile: ./deployments/docker/api-service.dockerfile
    restart: always
    ports:
      - 8084:8084
    env_file:
      - .env
    volumes:
      # - db_data:/data
      - db_data:/app/db
    # user: "65532:65532"
    deploy:
      mode: replicated
      replicas: 1

volumes:
  db_data: