CREATE TABLE IF NOT EXISTS logs_metadata (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL,
  level TEXT UNIQUE,
  user_id INTEGER UNIQUE,
  count INTEGER NOT NULL DEFAULT 0 CHECK (count >= 0)
);